### PR TITLE
Feature: Ability to handle user information for resume 

### LINKED ISSUE #1: Ability to handle user information for resume
Store the following information, with routes for adding and updating it.

- Name
- Phone Number (enforce international country code)
- Email Address

### PR DESCRIPTION
**Pull request by vantage-ola**
This PR aims to store the following information of the user, with routes for adding(POST) and updating(PUT) it. 

- Name
- Phone Number (enforce international country code)
- Email Address

resolves #1

### CODE REVIEW

**Comment by vantage-ola** [comment]
This pr aims to close issue #1

**Comment by vantage-ola** [comment]
@yashika51 would love you to do a review, thanks 🙏

**Comment by yashika51** [comment]
> @yashika51 would love you to do a review, thanks 🙏

Hi! Can you address the tests failing before we merge?

**Comment by vantage-ola** [comment]
If you inspect the tests, i wrote a  test suite that passed. the remaining tests(that are failing) and fixes has been resolved by #23

**Review by yashika51 — APPROVED** [review]

**Pull request merged**
