### PR TITLE
Improvements: Move json data variable to a json object file

### LINKED ISSUE #37: Make data variable a  json object file
Currently the `app.py` contains a json variable called 'data' . I think it would be better to move it to a '.json' object file.

### PR DESCRIPTION
**Pull request by vantage-ola**
Instead of having json data variable in the `app.py`, we can move it to a json file and load it. It aims to resolve #37

### CODE REVIEW

**Comment by vantage-ola** [comment]
@yashika51 pls review, thanks  , #23 aims to fix the failing tests. thanks :)

**Comment by vantage-ola** [comment]
i didnt even realise, it had conflicts, its fixed  now, thanks...

**Comment by yashika51** [comment]
> i didnt even realise it had conflicts, its fixed now, thanks...

We still have some failing tests, can you check it out?

**Comment by Shopiley** [comment]
@vantage-ola, the one linter test you're failing is because you have the name `unique_resume_data_fixture` as both a function name and a variable name. Try changing the function name to something else.

**Comment by vantage-ola** [comment]
Ohhh 😭😭😭
Will do that in time, thanks...

**Comment by vantage-ola** [comment]
@yashika51  good to go 😅

**Comment by yashika51** [comment]
> @yashika51 good to go 😅

some conflicts fix to do

**Comment by vantage-ola** [comment]
I might as well close this pr , im losing my mind already ....tchhhh

**Comment by vantage-ola** [comment]
@yashika51 i think it's good now

**Pull request merged**
