### PR TITLE
Feat: added all get all api and post request

### LINKED ISSUE #15: Implement API route to return all "Skills"
On the `/resume/skill` route, you should:

- [ ] Return the Skill list when a GET request is made. The return should be in a list format.

### LINKED ISSUE #16: Implement API route to add new "Skills"
On the `/resume/skill` route, you should:

- [ ] Return the index position of the new Skill in the Skill list when a POST request is made

### LINKED ISSUE #18: Implement API route to return all "Educations"
On the `/resume/education` route, you should:

- [ ] Return the Education list when a GET request is made. The return should be in a list format.

### LINKED ISSUE #19: Implement API route to add new "Education"
On the `/resume/education` route, you should:

- [ ] Return the index position of the new Education in the Education list when a POST request is made

### LINKED ISSUE #21: Implement API route to return all "Experiences"
On the `/resume/experience` route, you should:

- [ ] Return the Experience list when a GET request is made. The return should be in a list format.

### LINKED ISSUE #22: Implement API route to add new "Experience"
On the `/resume/experience` route, you should:

- [ ] Return the index position of the new Experience in the Experience list when a POST request is made

### PR DESCRIPTION
**Pull request by byhlel**
Resolves #21, Resolves #18, Resolves #15 
Resolves #22 , Resolves #16 , Resolves #19 
Quite direct implementation!

### CODE REVIEW

**Comment by byhlel** [comment]
Edited the pytest to make more sense to the json returned object.

Now testsuite passes for present cases!

**Review by citruscai — APPROVED** [review]
looks good to me!

**Comment by Shopiley** [comment]
Hi @byhlel, I think you need to tag one of the pod leaders/maintainers to review this so it can be merged.

**Comment by byhlel** [comment]
@yashika51 could you accept this PR? Thanks, it will fix CI/CD for future uses as well.

**Review by yashika51 — APPROVED** [review]

**Comment by yashika51** [comment]
> @yashika51 could you accept this PR? Thanks, it will fix CI/CD for future uses as well.

Can you fix the lint issue and then go ahead and merge it

**Comment by byhlel** [comment]
Following the PR I had to deal with merge conflicts therefore I believe you need to approve again @yashika51 .
Thank you

**Comment by yashika51** [comment]
> Following the PR I had to deal with merge conflicts therefore I believe you need to approve again @yashika51 . Thank you

would you like to include the fix to the linting issue in this PR as well?

**Comment by byhlel** [comment]
@yashika51 Should be good now

**Pull request merged**
